######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 5 21:49:42 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cc

QT += core
QT += widgets
